<?xml version="1.0" encoding="UTF-8"?>

<project
    xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>cloud.piranha.tck.servlet</groupId>
        <artifactId>project</artifactId>
        <version>1-SNAPSHOT</version>
    </parent>
    <groupId>tck.server.servlet</groupId>
    <artifactId>project</artifactId>
    <packaging>pom</packaging>
    <name>TCK Certification - Piranha Server - Servlet TCK</name>
    <properties>
        <arquillian.version>1.9.1.Final</arquillian.version>
        <jakarta.servlet-api.version>6.1.0</jakarta.servlet-api.version>
        <java.version>21</java.version>
        <junit.version>5.11.4</junit.version>
        <maven-compiler-plugin.version>3.13.0</maven-compiler-plugin.version>
        <maven-surefire-plugin.version>3.5.2</maven-surefire-plugin.version>
        <piranha.directory>piranha</piranha.directory>
        <piranha.version>25.1.0</piranha.version>        
        <servlet-tck.version>6.1.0</servlet-tck.version>
        <servlet-tck.downloadUrl>https://download.eclipse.org/ee4j/servlet/jakartaee11/staged/eftl/jakarta-servlet-tck-${servlet-tck.version}.zip</servlet-tck.downloadUrl>
        <sigtest-maven-plugin.version>2.2</sigtest-maven-plugin.version>
    </properties>
    <modules>
        <module>installer</module>
        <!-- <module>runner</module> -->
    </modules>
</project>
