<?xml version="1.0" encoding="UTF-8"?>

<project
    xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>cloud.piranha.tck.servlet</groupId>
        <artifactId>project</artifactId>
        <version>1-SNAPSHOT</version>
    </parent>
    <artifactId>servlet</artifactId>
    <packaging>pom</packaging>
    <name>Piranha Servlet TCK - Servlet TCK</name>
    <properties>
        <ant.home>${project.build.directory}/ant</ant.home>
        <piranha.home>${project.build.directory}/piranha</piranha.home>
        <signature.home>${project.build.directory}/signature</signature.home>
        <tck.home>${project.build.directory}/tck</tck.home>
        <test.home>${tck.home}/src/com/sun/ts/tests</test.home>
    </properties>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>cloud.piranha</groupId>
                <artifactId>bom</artifactId>
                <version>${piranha.version}</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-antrun-plugin</artifactId>
                <executions>
                    <execution>
                        <id>validate</id>
                        <phase>validate</phase>
                        <configuration>
                            <target>
                                <!-- download, unzip and rename TCK -->
                                <get src="https://www.eclipse.org/downloads/download.php?file=/ee4j/servlet/jakartaee11/staged/eftl/jakarta-servlet-tck-6.1.1.zip&amp;r=1"
                                     dest="${project.build.directory}/tck.zip"
                                     skipexisting="true"
                                     verbose="true"/>
                                <unzip src="${project.build.directory}/tck.zip"
                                       dest="${project.build.directory}"/>
                                <move file="${project.build.directory}/servlet-tck"
                                      tofile="${project.build.directory}/tck"/>
                            </target>
                        </configuration>
                        <goals>
                            <goal>run</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
