<?xml version="1.0" encoding="UTF-8"?>

<project
    xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>tck.server.servlet</groupId>
        <artifactId>project</artifactId>
        <version>1-SNAPSHOT</version>
    </parent>
    <artifactId>runner</artifactId>
    <packaging>pom</packaging>
    <name>TCK Certification - Piranha Server - Servlet TCK - Runner</name>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.jboss.arquillian</groupId>
                <artifactId>arquillian-bom</artifactId>
                <version>${arquillian.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <dependencies>
        <!--
    
            Jakarta Servlet API

        -->
        <dependency>
            <groupId>jakarta.servlet</groupId>
            <artifactId>jakarta.servlet-api</artifactId>
            <version>${jakarta.servlet-api.version}</version>
            <scope>compile</scope>
        </dependency>
        <!--

            Piranha Arquillian connector
               
        -->
        <dependency>
            <groupId>cloud.piranha.arquillian</groupId>
            <artifactId>piranha-arquillian-managed</artifactId>
            <version>${piranha.version}</version>
            <scope>test</scope>
        </dependency>
        <!--
        
            Servlet TCK dependencies

        -->
        <dependency>
            <groupId>jakarta.tck</groupId>
            <artifactId>servlet-tck-runtime</artifactId>
            <version>${servlet-tck.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>jakarta.tck</groupId>
            <artifactId>servlet-tck-util</artifactId>
            <version>${servlet-tck.version}</version>
            <scope>test</scope>
        </dependency>
        <!--

            Signature test plugin

        -->
        <dependency>
            <groupId>jakarta.tck</groupId>
            <artifactId>sigtest-maven-plugin</artifactId>
            <version>${sigtest-maven-plugin.version}</version>
            <scope>test</scope>
        </dependency>
        <!--

            JUnit
            
        -->
        <dependency>
            <groupId>org.jboss.arquillian.junit5</groupId>
            <artifactId>arquillian-junit5-container</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>                            
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven-compiler-plugin.version}</version>
                <configuration>
                    <release>${java.version}</release>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>install-piranha</id>
                        <phase>generate-test-resources</phase>
                        <goals>
                            <goal>unpack</goal>
                        </goals>
                        <configuration>
                            <artifactItems>
                                <artifactItem>
                                    <groupId>cloud.piranha.dist</groupId>
                                    <artifactId>piranha-dist-server</artifactId>
                                    <version>${piranha.version}</version>
                                    <type>zip</type>
                                    <overWrite>false</overWrite>
                                    <outputDirectory>${piranha.directory}</outputDirectory>
                                </artifactItem>
                            </artifactItems>
                        </configuration>
                    </execution>
                    <execution>
                        <id>install-servlet-api-artifact</id>
                        <phase>generate-test-resources</phase>
                        <goals>
                            <goal>copy</goal>
                        </goals>
                        <configuration>
                            <artifactItems>
                                <artifactItem>
                                    <groupId>jakarta.servlet</groupId>
                                    <artifactId>jakarta.servlet-api</artifactId>
                                    <type>jar</type>
                                    <overWrite>true</overWrite>
                                    <outputDirectory>${project.build.directory}/</outputDirectory>
                                    <destFileName>jakarta.servlet-api.jar</destFileName>
                                </artifactItem>
                            </artifactItems>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${maven-surefire-plugin.version}</version>
                <executions>
                    <execution>
                        <id>test</id>
                        <goals>
                            <goal>test</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <argLine>
                        -Duser.language=en
                        -Duser.country=US
                        -Djava.locale.providers=COMPAT,CLDR
                    </argLine>
                    <dependenciesToScan>
                        <dependenciesToScan>jakarta.tck:servlet-tck-runtime</dependenciesToScan>
                    </dependenciesToScan>
                    <systemProperties>
                        <servlet.tck.support.crossContext>false</servlet.tck.support.crossContext>
                        <servlet.tck.support.http2Push>false</servlet.tck.support.http2Push>
                        <servlet.tck.archive.print>true</servlet.tck.archive.print>
                        <jimage.dir>${project.build.directory}/jdk-bundle</jimage.dir>
                        <sigTestClasspath>${project.build.directory}/jakarta.servlet-api.jar:${project.build.directory}/jdk-bundle/java.base:${project.build.directory}/jdk-bundle/java.rmi:${project.build.directory}/jdk-bundle/java.sql:${project.build.directory}/jdk-bundle/java.naming</sigTestClasspath>
                    </systemProperties>
                </configuration>
            </plugin>            
        </plugins>
    </build>
</project>
