<?xml version="1.0" encoding="UTF-8"?>

<project
    xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>tck.server.servlet</groupId>
        <artifactId>project</artifactId>
        <version>1-SNAPSHOT</version>
    </parent>
    <artifactId>installer</artifactId>
    <packaging>pom</packaging>
    <name>TCK Certification - Piranha Server - Servlet TCK - Installer</name>
    <build>
        <plugins>
            <plugin>
                <groupId>com.googlecode.maven-download-plugin</groupId>
                <artifactId>download-maven-plugin</artifactId>
                <version>1.13.0</version>
                <executions>
                    <execution>
                        <id>download-servlet-tck</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>wget</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <url>${servlet-tck.downloadUrl}</url>
                    <unpack>true</unpack>
                    <outputDirectory>${project.build.directory}</outputDirectory>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-install-plugin</artifactId>
                <version>3.1.3</version>
                <executions>
                    <execution>
                        <id>install-servlet-tck-pom</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>install-file</goal>
                        </goals>
                        <configuration>
                            <file>${project.build.directory}/servlet-tck/artifacts/servlet-tck-${servlet-tck.version}.pom</file>
                            <groupId>jakarta.tck</groupId>
                            <artifactId>servlet-tck</artifactId>
                            <version>${servlet-tck.version}</version>
                            <packaging>pom</packaging>
                        </configuration>
                    </execution>
                    <execution>
                        <id>install-servlet-tck-runtime</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>install-file</goal>
                        </goals>
                        <configuration>
                            <file>${project.build.directory}/servlet-tck/artifacts/servlet-tck-runtime-${servlet-tck.version}.jar</file>
                            <groupId>jakarta.tck</groupId>
                            <artifactId>servlet-tck-runtime</artifactId>
                            <version>${servlet-tck.version}</version>
                            <packaging>jar</packaging>
                            <generatePom>true</generatePom>
                        </configuration>
                    </execution>
                    <execution>
                        <id>install-servlet-tck-util</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>install-file</goal>
                        </goals>
                        <configuration>
                            <file>${project.build.directory}/servlet-tck/artifacts/servlet-tck-util-${servlet-tck.version}.jar</file>
                            <groupId>jakarta.tck</groupId>
                            <artifactId>servlet-tck-util</artifactId>
                            <version>${servlet-tck.version}</version>
                            <packaging>jar</packaging>
                            <generatePom>true</generatePom>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
